version = 1
disable_existing_loggers = false


[formatter]

[formatters.ssv]
# Space-Separated Values
format = "%(levelname)-8s %(name)s %(asctime)-15s %(message)s"
datefmt = "%Y-%m-%dT%H:%M:%S"

[formatters.ltsv]
# Labeled Tab-separated Values
format = "time:%(asctime)s	level:%(levelname)s	process:%(process)s	module:%(module)s	method:%(funcName)s	message:%(message)s"
datefmt = "%Y-%m-%d %H:%M:%S"

[handlers]

[handlers.console]
class = "logging.StreamHandler"
level = "DEBUG"
formatter = "ssv"
stream = "ext://sys.stdout"

[handlers.app]
class = "logging.handlers.TimedRotatingFileHandler"
level = "INFO"
formatter = "ltsv"
filename = "var/log/app.log"

# 切り替えるタイミング単位(D: day)
when = 'D'
# when 毎(この場合は 1日毎)
interval = 1
# 保持数
backupCount = 31

[handlers.error]
class = "logging.handlers.TimedRotatingFileHandler"
level = "ERROR"
formatter = "ltsv"

filename = "var/log/err.log"
when = 'D'
interval = 1
backupCount = 31

[loggers]

[loggers.tool]
#level = "INFO"
level = "DEBUG"
handlers = [
  "console",
  "app",
  "error",
]
propagate = false

# end
